apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::057733667042:role/org/app/eks/app-role
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  serviceAccountName: app
  containers:
  - name: alpine
    image: alpine:latest
    command: ['tail', '-f', '/dev/null']